apiVersion: v1
kind: Pod
metadata:
  labels:
    label: tfa
    owner: pics
spec:
  activeDeadlineSeconds: 18000
  containers:
  - name: jnlp
    image: "image-registry.openshift-image-registry.svc:5000/dno--jenkins-csb-rhacm/tests-jenkins-agent:latest"
    workingDir: '/home/jenkins'
    env:
      - name: HOME
        value: '/home/jenkins'
    resources:
      limits:
        cpu: 500m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 256Mi
  - name: tfa-container
    # ubi9 and python
    image: 'quay.io/vboulos/acmqe-automation/pics:ubi9-python'
    registry: docker.io
    # imagePullSecrets: 'agent-image-secret'
    ttyEnabled: true
    alwaysPullImage: true
    command: [ 'sleep', '365d' ]
    workingDir: '/home/jenkins'
    env:
      - name: HOME
        value: '/home/jenkins'
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi